### ISSUE TITLE
Breaking on componetWillUnmount(): Cannot set property 'onload' of undefined     

### ISSUE THREAD

**Issue by gedhean** [sconstantinides/react-preload-image#1]
I was using `react-preload-image` with `lazy` mode on. When I click on an image that link to change route (I'm using react-router-dom) the whole app crashes with the above error. 

If `lazy` mode is off everything works pretty well.

**Comment by sconstantinides** [comment]
Sorry for the delay. This should be fixed in the latest release (1.0.7).
